//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionDemo.BankServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TransferMoney", ReplyAction="http://tempuri.org/IService1/TransferMoneyResponse")]
        void TransferMoney(int fromId, int toId, int amount, bool simulateError);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TransferMoney", ReplyAction="http://tempuri.org/IService1/TransferMoneyResponse")]
        System.Threading.Tasks.Task TransferMoneyAsync(int fromId, int toId, int amount, bool simulateError);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TransactionDemo.BankServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TransactionDemo.BankServiceRef.IService1>, TransactionDemo.BankServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TransferMoney(int fromId, int toId, int amount, bool simulateError) {
            base.Channel.TransferMoney(fromId, toId, amount, simulateError);
        }
        
        public System.Threading.Tasks.Task TransferMoneyAsync(int fromId, int toId, int amount, bool simulateError) {
            return base.Channel.TransferMoneyAsync(fromId, toId, amount, simulateError);
        }
    }
}
