<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Classwork_4_Application\Classwork_4_Application.csproj" />
    <ProjectReference Include="..\Classwork_4_Domain\Classwork_4_Domain.csproj" />
    <ProjectReference Include="..\Classwork_4_Infrastructure\Classwork_4_Infrastructure.csproj" />
  </ItemGroup>

</Project>
